image:
  repository: "ghcr.io/raydak-labs/configarr"
  tag: "latest"
  pullPolicy: "IfNotPresent"

schedule: "@daily"

env:
  TZ: "UTC"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
