apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taiflix-servarr-wire
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/your-username/taiflix.git"
    targetRevision: HEAD
    path: charts/servarr-wire
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
